### ISSUE TITLE
code --install-extension *badges*.vsix

### ISSUE THREAD

**Issue by jiangtao** [idleberg/vscode-badges#1]
```error
zsh: no matches found: badges-*.vsix
```

**Comment by idleberg** [comment]
The description you refer to works for the _packaged_ extension only. That means you have to download the `.vsix` file manually, then install it using the given command-line (make sure to use the actual name).

If you want to install the package from Marketplace using the commandline, use `code --install-extension idleberg.badges` instead!

**Comment by jiangtao** [comment]
Thanks @idleberg . I had installed the extension, but  it didn't work when I input the prefix `svg-`. Anything else to do ?

**Comment by idleberg** [comment]
Newer versions of VSCode have quick suggestions disabled, so need to enable them in your settings:

```json
"[markdown]": {
    "editor.quickSuggestions": true
}
```

…and I should mention this in the README 😉

**Comment by jiangtao** [comment]
666 👏 It works. Thanks
